### PR TITLE
WIP: electron quick feature flags

### PR DESCRIPTION
**Pull request by jsibbison-square**
lets devs change featureFlags in develop tools and used in electron. There must be a prebuilt library or something to do this surely?

### CODE REVIEW

**Comment by michaelneale** [comment]
developer console doesn't really work when running bundled application though?

**Comment by jsibbison-square** [comment]
> developer console doesn't really work when running bundled application though?

Ok neat that's a good point, but a menu/screen would, no prebuilt libs for that?

**Comment by michaelneale** [comment]
@jsibbison-square yeah I would think so but haven't seen anything yet (easiest way would be menu I think - no GUI needed for that?) or could be env var and a list of flags?

**Comment by jsibbison-square** [comment]
looking at menu alernatives

**Pull request closed without merging**
