### PR TITLE
[cli] Do better than thinking...

### PR DESCRIPTION
**Pull request by jsibbison-square**
I was seeing a lot of 'Thinking...' printing. Realised it was a perfect opportunity to insert some random goose-ness to keep things interesting.

image

### CODE REVIEW

**Review by Kvadratni — APPROVED** [review]
absolutely love it. HONK!

**Comment by Kvadratni** [comment]
Do you want to insert some Top GUN references in there too?

Here’s a list of Top Gun-inspired phrases that can replace standard "thinking" or "performing action" blurbs for your AI agent. These phrases will add a flair of confidence and urgency to its operations:

Thinking/Processing
"Engaging the radar lock..."
"Switching to targeting mode..."
"Scanning the horizon..."
"Running a systems check..."
"Eyes on the bogey..."
"Plotting the flight path..."
"Pulling up intel from the tower..."
"Looking for a clear shot..."
"Calibrating instruments..."
"Goose, what do you see?"


Performing Action
"Engines roaring, going supersonic..."
"Locked and loaded, firing away..."
"Engaging afterburners..."
"Target acquired, executing maneuver..."
"Deploying countermeasures..."
"Rolling inverted to get the shot..."
"Entering the danger zone..."
"Cutting through turbulence, stay sharp..."
"Cleared for landing—initiating sequence..."
"The sky’s clear—mission underway!"
These blurbs can be tailored to your AI agent's functionality for different operations, keeping things high-energy and thematic.

**Comment by jsibbison-square** [comment]
> Do you want to insert some Top GUN references in there too?

I don't really think so, I tried to keep things very family safe so no military references. Ideally its something fun for the community that they can insert their own list locally.

**Comment by Kvadratni** [comment]
> > Do you want to insert some Top GUN references in there too?
> 
> I don't really think so, I tried to keep things very family safe so no military references. Ideally its something fun for the community that they can insert their own list locally.

That is a consideration I haven't thought about. Good point.

**Pull request merged**
