### PR TITLE
feat: hid/show + tray + popover

### PR DESCRIPTION
**Pull request by michaelneale**
image

If you command Q, goose just hides but stays in tray

command shift G to bring up goose!

### CODE REVIEW

**Comment by alexhancock** [comment]
The launcher works for me - nice! Two things I notice though:

1. I think we should remove the menu bar icon completely if the user quits via that path, as that's common practice when the app is fully quit **via** the menu bar item. The menu bar item should go away. Right now I see it still remains + shows a blank window if I click "Show Window" again after quitting

So ideal state would be (click X on the window, keep menu bar item)
Quit via menu bar item, remove menu bar item

2. The icon looks big for me compared to others (and not switching to white stroke when computer is in dark mode, though that's a smaller thing)

Attaching screen showing both. I can look tomorrow if there aren't obvious answers!

Screenshot 2024-11-17 at 21 30 35

**Comment by michaelneale** [comment]
@alexhancock not sure I follow by "menu bar icon"?

**Comment by michaelneale** [comment]
next things to do/try @alexhancock:

* Menu bar icon fix
* Menu bar quit fix (I think?)
* hotkey I think should be control+option+command+G
* hotkey should open new spotlight style window asking for tasks - pressing enter results in a new window

**Comment by michaelneale** [comment]
@alexhancock ok a fair glut of changes - it now opens a spotlight style initial command window, which will then open its own window (show window will show them all). Want to take a look/play?

**Comment by michaelneale** [comment]
image - not entirely happy - but interesting. 

I do wonder if we do away with tabs and try something else (@baxen's thoughts): 

* When we start a goose task, it's a "job to do"
* That task is more like list of running "things"

image

almost like we want an interstitial screen which would show the goose windows (vs tabs) and then can click in to them? (will look for something like it to be clearer) 

todoist has an interesting task in progress thing: 

image

**Comment by michaelneale** [comment]
Some more elements from the design library to use: 

image
(for finished sessions)

image\
(would need a stack of these - one for each running session)

**Comment by michaelneale** [comment]
@alexhancock can we close this in favour of wing-to-wing?

**Comment by alexhancock** [comment]
Superceded by the work in progress in https://github.com/block/goose/tree/alexhancock/wing-to-wing

**Pull request closed without merging**
