### PR TITLE
feat: [gui] cancel manipulates message history

### PR DESCRIPTION
**Pull request by jsibbison-square**
When the user clicks cancel while goose is working:

# Scenario: The last message in the ui is a user message

The user message will be removed. Ideally we put the content back into the input box but calling `setInput` was breaking everything so I've deferred that aspect.

# Scenario: Ongoing tool calls

Each tool call gets marked as interrupted, providing context to the user and ai

image

### CODE REVIEW

**Comment by michaelneale** [comment]
@jsibbison-square can you update to v1.0 just to make sure with this? as it touches a few things (and its a complex component)

**Comment by michaelneale** [comment]
seems to work well @jsibbison-square - I do see a warning in the ts: 

image

may be nothing

**Comment by jsibbison-square** [comment]
@michaelneale fixed the warning by adding the Message type. Still seems to work :)

**Review by michaelneale — APPROVED** [review]
nice one seeing this through!

**Pull request merged**
