### PR TITLE
Fixed icon position

### PR DESCRIPTION
**Pull request by wesrblock**
It was an offset error based on the drop shadow.

I fixed it by converting to a png and editing in gimp, then running the following script to build the icns

```python
import os
import subprocess
from PIL import Image

# Resolutions needed for ICNS
ICON_SIZES = [
    (16, '16x16'),
    (32, '16x16@2x'),       # 16pt @2x
    (32, '32x32'),
    (64, '32x32@2x'),       # 32pt @2x
    (128, '128x128'),
    (256, '128x128@2x'),    # 128pt @2x
    (256, '256x256'),
    (512, '256x256@2x'),    # 256pt @2x
    (512, '512x512'),
    (1024, '512x512@2x'),   # 512pt @2x
]

def resize_png(input_path, output_path, size):
    """Resize the input PNG to the specified size and save it."""
    with Image.open(input_path) as img:
        # Ensure the image is in RGBA mode for transparency support
        img = img.convert("RGBA")
        resized_img = img.resize((size, size), Image.LANCZOS)
        resized_img.save(output_path, format='PNG')

def create_iconset(png_path):
    """Create a .iconset directory with all required icon sizes."""
    # Create iconset directory
    iconset_path = 'icon.iconset'
    if not os.path.exists(iconset_path):
        os.makedirs(iconset_path)

    # Generate each icon size
    for size, name in ICON_SIZES:
        output_path = os.path.join(iconset_path, f'icon_{name}.png')
        print(f"Generating {output_path} at {size}x{size}...")
        resize_png(png_path, output_path, size)

    return iconset_path

def create_icns(iconset_path):
    """Convert the iconset to ICNS using iconutil."""
    output_path = 'icon.icns'
    try:
        subprocess.run(['iconutil', '-c', 'icns', iconset_path], check=True)
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"iconutil failed: {e}")
    return output_path

def main():
    png_path = 'icon_2048.png'
    
    # Check if input file exists
    if not os.path.exists(png_path):
        print(f"Error: {png_path} not found!")
        return

    try:
        # Create iconset with all sizes
        iconset_path = create_iconset(png_path)
        
        # Convert to ICNS
        icns_path = create_icns(iconset_path)
        
        print(f"\nSuccessfully created {icns_path}")
        
        # Cleanup iconset directory
        subprocess.run(['rm', '-r', iconset_path])
        
    except Exception as e:
        print(f"Error: {str(e)}")
        return

if __name__ == '__main__':
    main()
```

### CODE REVIEW

**Review by alexhancock — APPROVED** [review]

**Comment by michaelneale** [comment]
this is now larger than other icons - so need some more buffer or something around it?

**Review by michaelneale — CHANGES_REQUESTED** [review]
This reverts to larger size - quite a bit larger than other desktop icons

image

**Comment by michaelneale** [comment]
@wesrblock not sure exactly what size it should be - not sure if this is electron or just some unwritten rule of desktop icons (emacs icon for example is larger than that box)

**Comment by wesrblock** [comment]
@michaelneale I went ahead and redrew the icon square, it should have the proper padding now. How does it look on your machine?

**Review by michaelneale — APPROVED** [review]
looks amazing @wesrblock !

**Pull request merged**
