### PR TITLE
refactor: move `download_tokenizers.sh` to a cargo build script

### PR DESCRIPTION
**Pull request by alecthomas**
This simplifies the build to just `cargo build`. Also added a rust-toolchain.toml file so that `rustup` will Just Work™️.

### CODE REVIEW

**Review by salman1993 — APPROVED** [review]
we can also remove `download_tokenizer_files.py` since its no longer being used

**Comment by alecthomas** [comment]
> we can also remove `download_tokenizer_files.py` since its no longer being used

I wasn't sure about that one, but done!

**Comment by alecthomas** [comment]
Mmm I don't _think_ that build failure is my fault? At least, I didn't touch the Desktop App workflow, only the release.

**Comment by alecthomas** [comment]
Moved this to #490, on a branch

**Pull request closed without merging**
