### PR TITLE
docs: adding Managing Goose Sessions guide

### PR DESCRIPTION
**Pull request by EbonyLouis**
## Reason
I noticed that members of our community have had questions about managing sessions with these commands, so it’s likely that our broader, external community could benefit from similar guidance.

## Documentation Covers
This guide provides detailed instructions on:

Starting, ending, saving, resuming, and deleting sessions.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208665181140610

### CODE REVIEW

**Review by lily-de — APPROVED** [review]
Love it!

**Comment by EbonyLouis** [comment]
Thanks @lily-de 💖

**Comment by EbonyLouis** [comment]
@michaelneale can I have a review/merge pls

**Comment by angiejones** [comment]
> @michaelneale can I have a review/merge pls

I got you

**Pull request merged**
